name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/fastapi-app
            sudo git pull origin main  # Pull latest changes
            source env/bin/activate  # Activate virtual environment
            sudo env/bin/python -m pip install -r requirements.txt  # Install dependencies
            sudo supervisorctl restart all  # Restart FastAPI server